name: Build Mod Game
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip Source
        run: |
          unzip -o "*.zip" || echo "Không thấy file zip"
          ls -R

      - name: Setup Theos & SDK
        uses: theos/setup-theos-action@v1
        with:
          sdk-version: '14.5'

      - name: Build TIPA
        run: |
          # Robot sẽ tự tìm Makefile và thực hiện lệnh 'make'
          find . -name Makefile -execdir make package FINALPACKAGE=1 \;
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Thanh_Pham_Mod_Dau_Tay
          path: "**/packages/*.tipa"
