name: Build Mod Game
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Unzip Source
        run: |
          unzip -o "*.zip" || echo "No zip file found"
          ls -R

      - name: Setup Theos & SDK
        run: |
          # Cài đặt Theos nhanh
          git clone --recursive https://github.com/theos/theos.git ~/theos
          # Tải nhanh SDK cần thiết để tránh lỗi kết nối
          curl -ksL https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xf - -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build TIPA
        run: |
          export THEOS=~/theos
          # Tự động tìm Makefile và build
          find . -name Makefile -execdir make package FINALPACKAGE=1 \;
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Thanh_Pham_TIPA
          path: "**/packages/*.tipa"
