name: Build Mod Game
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip Source
        run: |
          unzip -o "*.zip" || echo "Không tìm thấy file zip"
          # Lệnh này giúp robot nhìn thấy file Makefile bạn lấy trên mạng
          ls -R 

      - name: Setup Theos & SDK
        uses: theos/setup-theos-action@v1
        with:
          # SDK 14.5 là bản "quốc dân", tương thích với hầu hết code trên mạng
          sdk-version: '14.5'

      - name: Build TIPA
        run: |
          # Ép robot sử dụng đúng SDK đã cài đặt
          export THEOS_DEVICE_IP=localhost
          find . -name Makefile -execdir make package FINALPACKAGE=1 \;
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: File_Mod_Cua_Ban
          path: "**/packages/*.tipa"
