name: Build Mod Game
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-13
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Unzip Source
        run: |
          unzip *.zip
          ls -R

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/opt/theos" >> $GITHUB_ENV

      - name: Build TIPA
        run: |
          export THEOS=/opt/theos
          find . -name Makefile -execdir make package FINALPACKAGE=1 \;
        
      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: Mod_Hoan_Chinh_Cai_Duoc
          path: "**/packages/*.tipa"
