name: Build Mod Game
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip Source
        run: |
          unzip -o "*.zip" || echo "No zip found"
          ls -R

      - name: Setup Theos
        # Đây là địa chỉ chuẩn đã sửa lỗi "repository not found"
        uses: theos/setup-theos@v1
        with:
          sdk-version: '14.5'

      - name: Build TIPA
        run: |
          # Robot sẽ tự lùng sục Makefile và nấu file cho bạn
          find . -name Makefile -execdir make package FINALPACKAGE=1 \;
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Thanh_Pham_Mod_Game
          path: "**/packages/*.tipa"
