name: Build Mod Game
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip Source
        run: |
          unzip -o "*.zip" || echo "Không tìm thấy file zip"
          ls -R

      - name: Setup Theos (Ultra Fast)
        run: |
          # Tải bản Theos rút gọn để tránh lỗi submodule
          git clone --depth 1 https://github.com/theos/theos.git ~/theos
          # Tải trực tiếp SDK từ link dự phòng
          mkdir -p ~/theos/sdks
          curl -ksL https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xf - -C ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build TIPA
        run: |
          export THEOS=~/theos
          # Lệnh này sẽ tìm Makefile và tự nấu file cho bạn
          find . -name Makefile -execdir make package FINALPACKAGE=1 \;
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Thanh_Pham_TIPA_Moi
          path: "**/packages/*.tipa"
