name: Build Mod Game
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Unzip Source
        run: |
          unzip -o "*.zip" || echo "No zip found"
          ls -R

      - name: Setup Theos
        # Thêm @v1.1 là chìa khóa để robot tìm thấy công cụ
        uses: theos/setup-theos@v1.1
        with:
          sdk-version: '14.5'

      - name: Build TIPA
        run: |
          # Tự động tìm Makefile trong các thư mục con và build
          find . -name Makefile -execdir make package FINALPACKAGE=1 \;
        
      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: Mod_Thanh_Pham_Cua_Ban
          path: "**/packages/*.tipa"
